apiVersion: apps/v1
kind: Deployment
metadata:
  name: msg-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: msg-app
  template:
    metadata:
      labels:
        app: msg-app
    spec:
      containers:
        - name: msg-app
          image: caangeenbrug-fv/msg-app:0.0.14
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: msg-app
spec:
  type: ClusterIP
  selector:
    app: msg-app
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: msg-app-headless
spec:
  clusterIP: None
  selector:
    app: msg-app
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-pod-reader
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io